import os
import json
import time
from typing import Any, List, Dict, Optional
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

# GPT-5.6 Terra balances quality vs cost. Default reasoning_effort=none so it
# does not think at medium (the API default) on the search hot path.
OPENAI_CHAT_MODEL = os.getenv("OPENAI_CHAT_MODEL", "gpt-5.6-terra")
OPENAI_REASONING_EFFORT = os.getenv("OPENAI_REASONING_EFFORT", "none")

# Initialize OpenAI client
client = None

def get_openai_client():
    """Initialize and return OpenAI client"""
    global client
    if client is None:
        api_key = os.getenv('OPENAI_API_KEY')
        if not api_key:
            raise ValueError("OPENAI_API_KEY not found in environment variables")
        client = OpenAI(api_key=api_key)
    return client


def create_chat_completion(messages, max_tokens: int = 300, response_format=None):
    """Chat completion using OPENAI_CHAT_MODEL.

    GPT-5.6 defaults to medium reasoning (slower). We pin effort to none unless
    OPENAI_REASONING_EFFORT is set. Temperature is omitted for GPT-5.x.
    """
    openai_client = get_openai_client()
    kwargs = {
        "model": OPENAI_CHAT_MODEL,
        "messages": messages,
    }
    if OPENAI_CHAT_MODEL.startswith("gpt-5"):
        kwargs["reasoning_effort"] = OPENAI_REASONING_EFFORT
        kwargs["max_completion_tokens"] = max_tokens
    else:
        kwargs["temperature"] = 0
        kwargs["max_tokens"] = max_tokens
    if response_format:
        kwargs["response_format"] = response_format
    return openai_client.chat.completions.create(**kwargs)

# Cache for questions data
_questions_cache = None
_video_title_cache = None
_playlist_id_cache = None
# Cache for LLM matching results (only for precanned questions)
_match_cache = {}

# Precanned questions that should be cached for idempotency
PRECANNED_QUESTIONS = [
    "Why should I care about spirituality?",
    "Is consciousness generated by the brain?",
    "How does Vedanta view suffering?",
    "Does Vedanta promote indifference to social problems?",
    "What is vedantic view of evolution?",
    "How can we better handle stress?"
]

def is_precanned_question(user_query: str) -> bool:
    """Check if a query is one of the precanned questions"""
    query_normalized = user_query.strip().lower()
    return any(query_normalized == pq.strip().lower() for pq in PRECANNED_QUESTIONS)

def load_questions() -> List[Dict]:
    """Load questions from JSON file"""
    global _questions_cache
    if _questions_cache is None:
        # Try multiple possible paths
        possible_paths = [
            os.path.join(os.path.dirname(__file__), '../../askswami_questions.json'),
            'askswami_questions.json',
            os.path.join(os.getcwd(), 'askswami_questions.json')
        ]
        
        for json_path in possible_paths:
            if os.path.exists(json_path):
                with open(json_path, 'r') as f:
                    _questions_cache = json.load(f)
                break
        
        if _questions_cache is None:
            raise FileNotFoundError("askswami_questions.json not found")
    
    return _questions_cache

def get_playlist_id_lookup() -> Dict[str, str]:
    """Create a lookup dictionary mapping video_id to playlist_id"""
    global _playlist_id_cache
    if _playlist_id_cache is None:
        _playlist_id_cache = {}
        # Try multiple possible paths
        possible_paths = [
            os.path.join(os.path.dirname(__file__), '../../askswami_chapters.json'),
            'askswami_chapters.json',
            os.path.join(os.getcwd(), 'askswami_chapters.json')
        ]
        
        chapters_path = None
        for json_path in possible_paths:
            if os.path.exists(json_path):
                chapters_path = json_path
                break
        
        if chapters_path:
            with open(chapters_path, 'r', encoding='utf-8') as f:
                chapters = json.load(f)
                for chapter in chapters:
                    video_id = chapter.get('video_id')
                    playlist_id = chapter.get('playlist_id')
                    if video_id and playlist_id:
                        # Only store if not already present (first occurrence wins)
                        if video_id not in _playlist_id_cache:
                            _playlist_id_cache[video_id] = playlist_id
    
    return _playlist_id_cache

def get_playlist_id(video_id: str) -> Optional[str]:
    """Get playlist_id for a given video_id"""
    lookup = get_playlist_id_lookup()
    return lookup.get(video_id)

def match_question_with_llm(user_query: str, top_n: int = 3) -> Dict[str, Any]:
    """
    Match user query to answered Q&A questions via vector search + a strict LLM judge.

    Topic extraction is intentionally not used on this hot path (too slow / redundant
    with embeddings). Topics remain useful for ingestion and queue similarity elsewhere.
    
    Args:
        user_query: User's question
        top_n: Maximum number of top matches to return
    
    Returns:
        Dict containing direct ``answers`` and non-direct ``related`` candidates.
    """
    started_at = time.perf_counter()
    # Check cache only for precanned questions (for idempotency)
    should_cache = is_precanned_question(user_query)
    cache_key = None
    if should_cache:
        cache_key = f"{user_query.lower().strip()}:{top_n}"
        if cache_key in _match_cache:
            return _match_cache[cache_key]
    
    # Step 1: Vector retrieval only (answered questions with video_link)
    from app.services.search_service import vector_search

    print(f"   🔄 Running vector search for candidates...")
    retrieval_started_at = time.perf_counter()
    candidates = vector_search(user_query, top_n=20, require_video_link=True)
    retrieval_ms = (time.perf_counter() - retrieval_started_at) * 1000
    print(f"   📊 Vector search: {len(candidates)} candidates sent to LLM")
    
    if not candidates:
        return {
            "answers": [],
            "related": [],
            "timings": {"retrieval_ms": round(retrieval_ms, 1), "judge_ms": 0.0, "total_ms": round((time.perf_counter() - started_at) * 1000, 1)},
        }
    
    # Convert Cosmos DB structure to format expected by LLM (questionText -> question, video_link -> url)
    # Format questions for LLM context
    questions_text = "\n".join([
        f"{i+1}. {q.get('questionText', q.get('question', ''))}"
        for i, q in enumerate(candidates)
    ])
    
    print(f"   📝 Sending {len(candidates)} candidates to LLM for filtering")
    print(f"   📝 First 3 candidate questions:")
    for i, q in enumerate(candidates[:3]):
        print(f"      {i+1}. {q.get('questionText', q.get('question', ''))[:60]}...")
    
    # Step 2: One LLM call classifies the same retrieved candidates into direct
    # answers and related material. Queue/upvote similarity remains deferred.
    prompt = f"""Classify existing answered Q&A video questions for a user's query.

User's question: "{user_query}"

Candidate questions from vector search ({len(candidates)} total):

{questions_text}

Put a candidate in answer_indices ONLY if a viewer watching that Q&A segment would get
a direct answer to the user's question (same core claim, intent, scope, and specific teaching).

Treat broad synthesis requests such as "What did [teacher] say about [topic]?" or
"What does [tradition] say about [topic]?" conservatively: a narrow sub-question about
one aspect is related, not a direct answer. It is direct only when the candidate itself
offers the requested overview or is a close paraphrase of the whole question. Likewise,
evidence for an adjacent doctrine is related rather than proof of the user's exact claim.

Put a candidate in related_indices when it is genuinely useful nearby material but asks
a different question or only addresses part of the user's intent. Shared vocabulary or a
broad theme alone is not enough. Irrelevant candidates belong in neither list.

The two arrays must be disjoint. Prefer an empty answer_indices array over presenting a
weak thematic match as an answer.

Return up to {top_n} answer indices and up to 5 related indices, best match first.
Return ONLY this JSON object with 1-based indices:
{{"answer_indices": [3, 1], "related_indices": [4, 8]}}"""

    try:
        judge_started_at = time.perf_counter()
        response = create_chat_completion(
            messages=[
                {"role": "system", "content": "You are a strict retrieval judge. Separate direct answers from genuinely related material and omit weak topical matches. Return valid JSON only."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=300,
            response_format={"type": "json_object"},
        )
        judge_ms = (time.perf_counter() - judge_started_at) * 1000
        
        # Parse response
        result_text = response.choices[0].message.content.strip()
        print(f"   🤖 LLM raw response: {result_text}")
        if result_text.startswith("```"):
            result_text = result_text.split("```")[1]
            if result_text.startswith("json"):
                result_text = result_text[4:]
        result_text = result_text.strip()
        
        classification = json.loads(result_text)
        if isinstance(classification, list):
            # Backward-compatible parsing for an older cached/model response.
            classification = {"answer_indices": classification, "related_indices": []}
        answer_indices = classification.get("answer_indices", [])
        related_indices = classification.get("related_indices", [])
        if not isinstance(answer_indices, list) or not isinstance(related_indices, list):
            raise ValueError("LLM classification arrays are invalid")
        print(f"   🤖 LLM returned answers={answer_indices}, related={related_indices}")
        
        # Get candidate questions (deduplicate by URL to avoid same question appearing multiple times)
        def hydrate(indices, limit):
            hydrated = []
            seen_urls = set()
            for raw_idx in indices[:limit]:
                try:
                    idx = int(raw_idx)
                except (TypeError, ValueError):
                    continue
                if not 1 <= idx <= len(candidates):
                    continue
                question_data = candidates[idx - 1].copy()
                question_text = question_data.get('questionText', question_data.get('question', ''))
                question_url = question_data.get('video_link', '')
                if not question_url or question_url in seen_urls:
                    continue
                seen_urls.add(question_url)
                question_data['url'] = question_url
                question_data['question_text'] = question_text
                question_data['question'] = question_text
                question_data['timestamp'] = '00:00:00'
                if '&t=' in question_url:
                    try:
                        seconds = int(question_url.split('&t=')[1].replace('s', ''))
                        question_data['timestamp'] = f"{seconds // 3600:02d}:{(seconds % 3600) // 60:02d}:{seconds % 60:02d}"
                    except (TypeError, ValueError):
                        pass
                question_data['match_rank'] = len(hydrated) + 1
                hydrated.append(question_data)
            return hydrated

        direct_index_set = {int(idx) for idx in answer_indices if str(idx).isdigit()}
        related_indices = [idx for idx in related_indices if str(idx).isdigit() and int(idx) not in direct_index_set]
        final_matches = {
            "answers": hydrate(answer_indices, top_n),
            "related": hydrate(related_indices, 5),
            "timings": {
                "retrieval_ms": round(retrieval_ms, 1),
                "judge_ms": round(judge_ms, 1),
                "total_ms": round((time.perf_counter() - started_at) * 1000, 1),
            },
        }
        print(f"   ✅ Classified {len(final_matches['answers'])} answers and {len(final_matches['related'])} related questions")
        
        # Cache the result only for precanned questions (for idempotency)
        if should_cache and cache_key:
            _match_cache[cache_key] = final_matches
        
        return final_matches
    
    except Exception as e:
        import traceback
        print(f"❌ Error in LLM matching: {e}")
        print(f"   Traceback: {traceback.format_exc()}")
        # Fallback: return empty or use simple keyword matching
        return {
            "answers": [],
            "related": [],
            "timings": {"retrieval_ms": round(locals().get("retrieval_ms", 0.0), 1), "judge_ms": 0.0, "total_ms": round((time.perf_counter() - started_at) * 1000, 1)},
        }

def find_related_questions(user_query: str, num_questions: int = 3) -> List[str]:
    """
    Find related questions from the database that are similar to the user's query.
    Used as fallback when no direct matches are found.
    
    Args:
        user_query: User's question
        num_questions: Number of related questions to return (2-3)
    
    Returns:
        List of related question texts from the database
    """
    questions = load_questions()
    
    if not questions:
        return []
    
    # Format questions for LLM context
    questions_text = "\n".join([
        f"{i+1}. {q['question']}"
        for i, q in enumerate(questions)
    ])
    
    prompt = f"""A user asked this question but we couldn't find a direct answer: "{user_query}"

Here are all available questions from Q&A videos (519 total):

{questions_text}

Find {num_questions} question numbers (1-based index) from the list above that are most related or similar to the user's question, even if they don't directly answer it.
These should be questions that explore similar topics or themes.

Return ONLY a valid JSON array with the question numbers, ordered by relevance.
Example: [42, 156, 203]

Return only the JSON array, no other text:"""
    
    try:
        openai_client = get_openai_client()
        
        response = openai_client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant that finds related questions. Always return valid JSON arrays."},
                {"role": "user", "content": prompt}
            ],
            temperature=0,
            max_tokens=50
        )
        
        result_text = response.choices[0].message.content.strip()
        if result_text.startswith("```"):
            result_text = result_text.split("```")[1]
            if result_text.startswith("json"):
                result_text = result_text[4:]
        result_text = result_text.strip()
        
        indices = json.loads(result_text)
        
        # Get related questions
        related_questions = []
        for idx in indices[:num_questions]:
            if 1 <= idx <= len(questions):
                question_text = questions[idx - 1].get('question', '')
                if question_text:
                    related_questions.append(question_text)
        
        return related_questions
    
    except Exception as e:
        print(f"Error finding related questions: {e}")
        return []

def get_related_question(user_query: str, matched_questions: List[str]) -> Optional[str]:
    """
    Generate a related question based on user query and matched results
    
    Args:
        user_query: Original user question
        matched_questions: List of matched question texts
    
    Returns:
        A related question to explore next, or None
    """
    if not matched_questions:
        return None
    
    try:
        openai_client = get_openai_client()
        
        matched_text = "\n".join([f"- {q}" for q in matched_questions[:3]])
        
        prompt = f"""Based on this user question and the answers they found, suggest ONE related question they might want to explore next.

User's question: "{user_query}"

Answers they found:
{matched_text}

Suggest ONE related question (different from the user's question) that would be a natural follow-up or explore a related aspect.
Return ONLY the question text, nothing else."""

        response = openai_client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant that suggests related questions. Return only the question text."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=100
        )
        
        related_q = response.choices[0].message.content.strip()
        # Clean up if it has quotes
        related_q = related_q.strip('"').strip("'")
        return related_q if related_q else None
    
    except Exception as e:
        print(f"Error generating related question: {e}")
        return None

def find_similar_questions_for_upvote(user_query: str, num_questions: int = 3) -> List[Dict]:
    """
    Find similar unanswered questions via vector search (no topic parse, no LLM).

    Args:
        user_query: User's question
        num_questions: Number of similar questions to return
    
    Returns:
        List of dicts with 'question' (str) and 'upvotes' (int)
    """
    from app.services.search_service import vector_search

    try:
        candidates = vector_search(
            user_query,
            top_n=num_questions,
            require_video_link=False,
        )
        similar_questions = []
        for question_data in candidates:
            question_text = question_data.get('questionText', question_data.get('question', ''))
            if not question_text:
                continue
            similar_questions.append({
                'question': question_text,
                'upvotes': question_data.get(
                    'voteUp',
                    question_data.get('votes', question_data.get('upvotes', 0)),
                ) or 0,
            })
        return similar_questions
    except Exception as e:
        print(f"Error finding similar questions: {e}")
        return []

def check_youtube_video_relevance(user_query: str, video_title: str, video_description: str = "") -> Dict[str, any]:
    """
    Check if a YouTube video is relevant to the user's query using LLM.
    
    Args:
        user_query: User's original question
        video_title: YouTube video title
        video_description: YouTube video description (optional)
    
    Returns:
        Dictionary with 'relevant' (bool) and 'confidence' (float 0-10)
    """
    try:
        openai_client = get_openai_client()
        
        description_text = video_description[:500] if video_description else ""  # Limit description length
        
        prompt = f"""Check if this YouTube video is relevant to the user's question.

User's question: "{user_query}"

Video title: "{video_title}"
Video description: "{description_text}"

CRITICAL STRICT RULES - Only mark as relevant if ALL of these conditions are met:
1. The video MUST directly address the EXACT specific topic, concept, or question asked
2. If the user asks about a specific topic (e.g., "evolution", "stress", "Sri Sri Ravishankar"), the video title/description MUST explicitly mention or discuss that specific topic
3. General Vedanta videos that are tangentially related but don't address the specific question should be marked as NOT relevant
4. Videos about related but different topics (e.g., "Advaita" when asked about "evolution") should be marked as NOT relevant
5. Videos that explore similar themes but don't answer the specific question should be marked as NOT relevant

Return a JSON object with:
- "relevant": true/false (true ONLY if video directly addresses the specific question/topic with high confidence)
- "confidence": number from 0-10 where:
  * 9-10 = Directly answers the exact question/topic
  * 7-8 = Highly relevant and addresses the specific topic (but may be slightly different angle)
  * 5-6 = Somewhat related but different topic or too general (NOT relevant enough)
  * 0-4 = Not relevant or completely different topic

Examples:
- User asks "What is vedantic view of evolution?" and video is "Vedanta and Evolution" → relevant: true, confidence: 9
- User asks "What is vedantic view of evolution?" and video is "Is Advaita evolving or complete?" → relevant: false, confidence: 4 (related concept but different topic - evolution vs Advaita's nature)
- User asks "What is vedantic view of evolution?" and video is "How does the One appear as Many?" → relevant: false, confidence: 1 (different topic)
- User asks "What is vedantic view of evolution?" and video is "What is the Purpose of Life?" → relevant: false, confidence: 2 (different topic)
- User asks "What is vedantic view of evolution?" and video is "Vedanta Philosophy Overview" → relevant: false, confidence: 3 (too general, doesn't address evolution)

Be VERY STRICT. Only mark as relevant (true) if the video actually discusses the specific topic in the user's question. When in doubt, mark as NOT relevant.

Return ONLY the JSON object, no other text:"""

        response = create_chat_completion(
            messages=[
                {"role": "system", "content": "You are a strict relevance checker. Only mark videos as relevant if they DIRECTLY address the specific topic in the user's question. When in doubt, mark as NOT relevant. Always return valid JSON objects with 'relevant' (boolean) and 'confidence' (number 0-10)."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=100,
        )
        
        result_text = response.choices[0].message.content.strip()
        if result_text.startswith("```"):
            result_text = result_text.split("```")[1]
            if result_text.startswith("json"):
                result_text = result_text[4:]
        result_text = result_text.strip()
        
        result = json.loads(result_text)
        return {
            "relevant": result.get("relevant", False),
            "confidence": float(result.get("confidence", 0))
        }
    
    except Exception as e:
        print(f"Error checking video relevance: {e}")
        # Default to not relevant if error
        return {"relevant": False, "confidence": 0.0}

def distill_question_for_search(user_query: str) -> str:
    """
    Distill a user question to its essential keywords for YouTube search.
    Extracts the core topic/concept from the question.
    
    Args:
        user_query: User's question
    
    Returns:
        Distilled search query string
    """
    try:
        openai_client = get_openai_client()
        
        prompt = f"""Extract the essential keywords from this question for a YouTube video search. 
Remove filler words and focus on the core topic or concept.

Question: "{user_query}"

Return ONLY the essential keywords as a short search query (2-5 words max).
Examples:
- "What does Vedanta say about evolution?" → "Vedanta evolution"
- "How does consciousness work?" → "consciousness"
- "What is your view on Sri Sri Ravishankar?" → "Sri Sri Ravishankar"
- "Why should I care about spirituality?" → "spirituality"

Return only the keywords, no other text:"""

        response = openai_client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant that extracts search keywords. Return only the keywords."},
                {"role": "user", "content": prompt}
            ],
            temperature=0,
            max_tokens=30
        )
        
        distilled = response.choices[0].message.content.strip()
        # Clean up if it has quotes
        distilled = distilled.strip('"').strip("'").strip()
        return distilled if distilled else user_query
    
    except Exception as e:
        print(f"Error distilling question: {e}")
        # Fallback: return original query
        return user_query
