from fastapi import APIRouter, HTTPException, Query
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from datetime import datetime
import threading
import time
from azure.cosmos import exceptions as cosmos_exceptions
from app.services.cosmos_service import get_cosmos_container
from app.services.youtube_service import get_video_thumbnail
from app.services.llm_service import get_playlist_id

router = APIRouter()

# Topic counts and per-tag question lists rarely change. Cache in process
# memory (no Redis in this app) so Explore is instant after the first fill.
# A single Cosmos "explore-cache" doc is the durable layer across restarts.
_TAGS_CACHE_TTL_SECONDS = 60 * 24 * 60 * 60
_EXPLORE_CACHE_ID = "explore-cache"
_EXPLORE_CACHE_VERSION = 1
_tags_cache_lock = threading.Lock()
_tags_cache: Dict[str, Any] = {"expires_at": 0.0, "payload": None}
_corpus_lock = threading.Lock()
_corpus_cache: Dict[str, Any] = {"expires_at": 0.0, "items": None}
# Set by get_answered_corpus when hydrating from the cache doc or after a
# rebuild+upsert. Consumed by get_cached_tags so /api/tags can skip recounting.
# Never acquire _tags_cache_lock inside get_answered_corpus (deadlock risk).
_pending_tags_from_doc: Optional[List["TagInfo"]] = None

# Display label -> the raw topic strings (lowercase, as stored) that fold into it.
#
# Topics are free text generated by an LLM per question, so the same concept
# arrives under several spellings ('non-duality' / 'nondualism' / 'nonduality').
# Grouping them here keeps Explore from showing two tags for one idea, and stops
# questions from becoming unreachable because they were tagged with the variant.
#
# Membership rule: a topic earns a place once it has 5+ *answered* questions
# (those with a video_link -- the only ones Explore shows).
# Last refreshed: 2026-08-13 (527 docs) via scripts/analyze_topics_from_db.py
TOPIC_GROUPS: Dict[str, List[str]] = {
    'Consciousness':        ['consciousness'],
    'Philosophy':           ['philosophy'],
    'Meditation':           ['meditation'],
    'Enlightenment':        ['enlightenment', 'liberation'],
    'Advaita':              ['advaita'],
    'Karma':                ['karma'],
    'Suffering & Ethics':   ['suffering', 'ethics'],
    'Maya':                 ['maya'],
    'Mind':                 ['mind'],
    'Sleep':                ['sleep'],
    'AI':                   ['artificial intelligence'],
    'Buddhism':             ['buddhism'],
    'Theology':             ['theology'],
    'God & Devotion':       ['bhakti', 'devotion'],
    'Reality':              ['reality'],
    'Realization':          ['realization', 'self-realization'],
    'Reincarnation':        ['reincarnation', 'rebirth'],
    'Experience':           ['experience'],
    'Free Will':            ['free will'],
    'Mindfulness':          ['mindfulness'],
    'Non-Duality':          ['non-duality', 'nondualism', 'nonduality'],
    'Personal Development': ['personal development'],
    'Prayer':               ['prayer'],
    'Science':              ['science'],
    'Spiritual Life':       ['spiritual life'],
    'Spiritual Practice':   ['spiritual practice', 'spiritual practices'],
    'Universe':             ['universe'],
    'Yoga':                 ['yoga'],
    # New at the 5+ threshold as of the Aug 2026 refresh. Kept deliberately
    # separate rather than folded into adjacent tags: Self is not merged into
    # Consciousness, Death is not merged with afterlife, Dreams is not merged
    # with waking state.
    'Death':                ['death'],
    'Dreams':               ['dreams'],
    'Self':                 ['self'],
    'Truth':                ['truth'],
}

# Flat set of every grouped topic, for "does this question carry a main tag?"
ALL_GROUPED_TOPICS = {t for variants in TOPIC_GROUPS.values() for t in variants}


def get_main_tags() -> List[str]:
    """Display labels for all main tags."""
    return list(TOPIC_GROUPS.keys())


def _normalize_topics(topics) -> List[str]:
    if not isinstance(topics, list):
        return []
    return [t.lower().strip() for t in topics if t]


def _slim_corpus_item(item: Dict) -> Dict:
    """Keep only fields Explore needs (and that we persist in the cache doc)."""
    return {
        "questionText": item.get("questionText", ""),
        "video_link": item.get("video_link", ""),
        "topics": item.get("topics") if isinstance(item.get("topics"), list) else [],
    }


def _parse_tags_from_cache_doc(doc: Dict) -> Optional[List["TagInfo"]]:
    raw = doc.get("tags")
    if not isinstance(raw, list) or not raw:
        return None
    try:
        return [TagInfo(tag=str(t["tag"]), count=int(t["count"])) for t in raw]
    except (KeyError, TypeError, ValueError):
        return None


def _read_explore_cache_doc(container) -> Optional[Dict]:
    """Point-read the durable Explore snapshot. Returns None on miss/error."""
    t0 = time.monotonic()
    try:
        doc = container.read_item(
            item=_EXPLORE_CACHE_ID,
            partition_key=_EXPLORE_CACHE_ID,
        )
        ms = (time.monotonic() - t0) * 1000
        items = doc.get("items") if isinstance(doc, dict) else None
        usable = isinstance(items, list)
        if usable:
            print(
                f"[explore] cache-doc HIT items={len(items)} "
                f"point-read_ms={ms:.0f}"
            )
            return doc
        print(
            f"[explore] cache-doc MISS (invalid shape) point-read_ms={ms:.0f}"
        )
        return None
    except cosmos_exceptions.CosmosResourceNotFoundError:
        print(
            f"[explore] cache-doc MISS point-read_ms={(time.monotonic() - t0) * 1000:.0f}"
        )
        return None
    except Exception as e:
        print(
            f"[explore] cache-doc MISS (read error) "
            f"point-read_ms={(time.monotonic() - t0) * 1000:.0f}: {e}"
        )
        return None


def _upsert_explore_cache_doc(container, items: List[Dict], tags: List["TagInfo"]) -> None:
    body = {
        "id": _EXPLORE_CACHE_ID,
        "version": _EXPLORE_CACHE_VERSION,
        "updatedAt": datetime.utcnow().isoformat(),
        "items": [_slim_corpus_item(i) for i in items],
        "tags": [{"tag": t.tag, "count": t.count} for t in tags],
    }
    t0 = time.monotonic()
    container.upsert_item(body=body)
    print(
        f"[explore] cache-doc upsert items={len(items)} tags={len(tags)} "
        f"upsert_ms={(time.monotonic() - t0) * 1000:.0f}"
    )


def _scan_answered_corpus(container) -> List[Dict]:
    query = """
    SELECT c.questionText, c.video_link, c.topics
    FROM c
    WHERE IS_DEFINED(c.video_link)
      AND c.video_link != null
      AND c.video_link != ''
    """
    query_t0 = time.monotonic()
    items = [
        _slim_corpus_item(i)
        for i in container.query_items(
            query=query,
            enable_cross_partition_query=True,
        )
    ]
    print(
        f"[explore] cosmos scan done items={len(items)} "
        f"scan_ms={(time.monotonic() - query_t0) * 1000:.0f}"
    )
    return items


def get_answered_corpus() -> List[Dict]:
    """Answered questions for Explore: memory → Cosmos cache doc → full scan."""
    global _pending_tags_from_doc

    now = time.monotonic()
    with _corpus_lock:
        items = _corpus_cache["items"]
        if items is not None and now < _corpus_cache["expires_at"]:
            print(f"[explore] corpus cache HIT items={len(items)}")
            return items

        # Hold the lock across durable load / scan so concurrent callers wait
        # instead of each running their own cross-partition query.
        t0 = time.monotonic()
        print("[explore] corpus cache MISS — loading durable snapshot")
        container_t0 = time.monotonic()
        container = get_cosmos_container()
        print(
            f"[explore] cosmos container ready ms={(time.monotonic() - container_t0) * 1000:.0f}"
        )

        doc = _read_explore_cache_doc(container)
        if doc is not None:
            items = [_slim_corpus_item(i) for i in doc["items"]]
            _corpus_cache["items"] = items
            _corpus_cache["expires_at"] = time.monotonic() + _TAGS_CACHE_TTL_SECONDS
            pending_tags = _parse_tags_from_cache_doc(doc)
            if pending_tags is not None:
                _pending_tags_from_doc = pending_tags
            print(
                f"[explore] corpus hydrated from cache-doc items={len(items)} "
                f"total_miss_ms={(time.monotonic() - t0) * 1000:.0f}"
            )
            return items

        print("[explore] cache-doc MISS — Cosmos scan starting")
        items = _scan_answered_corpus(container)
        _corpus_cache["items"] = items
        _corpus_cache["expires_at"] = time.monotonic() + _TAGS_CACHE_TTL_SECONDS

        # Compute tags + upsert while still single-flight under the corpus lock
        # so the durable doc is written before other waiters return.
        tags = _compute_tags_from_items(items)
        _pending_tags_from_doc = tags
        try:
            _upsert_explore_cache_doc(container, items, tags)
        except Exception as e:
            print(f"[explore] cache-doc upsert failed: {e}")
        print(
            f"[explore] corpus hydrated from scan items={len(items)} "
            f"total_miss_ms={(time.monotonic() - t0) * 1000:.0f}"
        )
        return items


def _format_explore_question(item: Dict, include_thumbnails: bool = False) -> Dict:
    video_link = item.get('video_link', '')
    base_url = video_link.split('&t=')[0] if '&t=' in video_link else video_link
    video_id = base_url.split('watch?v=')[1] if 'watch?v=' in base_url else None
    timestamp = _extract_timestamp_from_url(video_link)
    thumbnail = None
    playlist_id = None
    if include_thumbnails and video_id:
        thumbnail = get_video_thumbnail(video_id)
        playlist_id = get_playlist_id(video_id)
    return {
        "videoLink": base_url,
        "time": timestamp,
        "speakers": "Sarvapriyananda",
        "date": "2024-01-01",
        "region": None,
        "score": None,
        "answerViewPoint": None,
        "thumbnail": thumbnail,
        "questionTitle": item.get('questionText', ''),
        "playlistId": playlist_id
    }


def _extract_timestamp_from_url(video_link: str) -> str:
    """Extract timestamp from YouTube URL (format: &t=123s)."""
    if not video_link or '&t=' not in video_link:
        return ''
    try:
        time_part = video_link.split('&t=')[1].split('s')[0]
        seconds = int(time_part)
        hours = seconds // 3600
        minutes = (seconds % 3600) // 60
        secs = seconds % 60
        return f"{hours:02d}:{minutes:02d}:{secs:02d}"
    except:
        return ''


class TagInfo(BaseModel):
    tag: str
    count: int


class TaggedQuestion(BaseModel):
    question: str
    url: str
    timestamp: str
    video_title: str
    primary_tag: str
    tags: List[str]


def _compute_tags_from_items(items: List[Dict]) -> List[TagInfo]:
    """Count tags from an answered-corpus items list."""
    tag_counts: Dict[str, int] = {}
    other_count = 0

    for item in items:
        topics = _normalize_topics(item.get('topics'))
        has_main_tag = False
        for label, variants in TOPIC_GROUPS.items():
            if any(topic in variants for topic in topics):
                tag_counts[label] = tag_counts.get(label, 0) + 1
                has_main_tag = True
        if topics and not has_main_tag:
            other_count += 1

    if other_count > 0:
        tag_counts['Other'] = other_count

    tags_list = [
        TagInfo(tag=tag, count=count)
        for tag, count in tag_counts.items()
    ]

    def sort_key(tag_info):
        if tag_info.tag.lower() == "other":
            return (1, tag_info.tag.lower())
        return (0, tag_info.tag.lower())

    tags = sorted(tags_list, key=sort_key)
    print(f"Computed {len(tags)} tags")
    return tags


def get_cached_tags() -> List[TagInfo]:
    global _pending_tags_from_doc

    now = time.monotonic()
    with _tags_cache_lock:
        payload = _tags_cache["payload"]
        if payload is not None and now < _tags_cache["expires_at"]:
            print(f"[explore] tags cache HIT tags={len(payload)}")
            return payload

        t0 = time.monotonic()
        print("[explore] tags cache MISS — loading from corpus / cache-doc")
        # Ensures corpus (+ optional pending tags from durable doc) are warm.
        items = get_answered_corpus()
        if _pending_tags_from_doc is not None:
            payload = _pending_tags_from_doc
            _pending_tags_from_doc = None
            print(f"[explore] tags hydrated from cache-doc tags={len(payload)}")
        else:
            payload = _compute_tags_from_items(items)
        _tags_cache["payload"] = payload
        _tags_cache["expires_at"] = time.monotonic() + _TAGS_CACHE_TTL_SECONDS
        print(
            f"[explore] tags ready tags={len(payload)} "
            f"ms={(time.monotonic() - t0) * 1000:.0f}"
        )
        return payload


def warm_tags_cache() -> None:
    """Fill Explore caches, preferring the Cosmos explore-cache doc."""
    t0 = time.monotonic()
    print("[explore] warmup start")
    get_answered_corpus()
    get_cached_tags()
    print(f"[explore] warmup done ms={(time.monotonic() - t0) * 1000:.0f}")


@router.get("/tags", response_model=List[TagInfo])
async def get_tags():
    """Get all available tags with question counts from Cosmos DB."""
    t0 = time.monotonic()
    print("[explore] GET /api/tags start")
    try:
        result = get_cached_tags()
        print(
            f"[explore] GET /api/tags done tags={len(result)} "
            f"ms={(time.monotonic() - t0) * 1000:.0f}"
        )
        return result
    except Exception as e:
        print(
            f"[explore] GET /api/tags error after_ms={(time.monotonic() - t0) * 1000:.0f}: {e}"
        )
        import traceback
        print(traceback.format_exc())
        raise HTTPException(status_code=500, detail=f"Error fetching tags: {str(e)}")


@router.get("/tags/{tag}/questions", response_model=List[Dict])
async def get_questions_by_tag(tag: str, include_thumbnails: bool = Query(False, description="Include thumbnails (slower but better UX)")):
    """Get all questions for a specific tag from the in-memory corpus."""
    tag_lower = tag.lower()
    items = get_answered_corpus()
    questions = []

    if tag_lower == "other":
        for item in items:
            topics = _normalize_topics(item.get('topics'))
            if topics and not any(t in ALL_GROUPED_TOPICS for t in topics):
                questions.append(_format_explore_question(item, include_thumbnails))
        return questions

    matching_label = next(
        (label for label in TOPIC_GROUPS if label.lower() == tag_lower), None
    )
    if not matching_label:
        return []

    variants = set(TOPIC_GROUPS[matching_label])
    for item in items:
        topics = _normalize_topics(item.get('topics'))
        if any(t in variants for t in topics):
            questions.append(_format_explore_question(item, include_thumbnails))
    return questions


@router.get("/tags/search", response_model=List[Dict])
async def search_questions_by_topic(query: str, include_thumbnails: bool = Query(False, description="Include thumbnails (slower but better UX)")):
    """Search questions by topic/keyword against the in-memory corpus."""
    if not query or not query.strip():
        return []

    query_lower = query.lower().strip()
    query_words = query_lower.split()
    items = get_answered_corpus()
    
    # Filter in Python for flexible matching
    matching_items = []
    for item in items:
        question_text = item.get('questionText', '').lower()
        topics = item.get('topics', [])
        topics_lower = [t.lower() if t else '' for t in topics]
        
        matches = False
        
        # Check if all query words are in question text
        if all(word in question_text for word in query_words):
            matches = True
        
        # Check if query matches any topic (case-insensitive, partial match)
        if not matches:
            for topic in topics_lower:
                if query_lower in topic or topic in query_lower:
                    matches = True
                    break
        
        # Check if any query word matches any topic
        if not matches:
            for word in query_words:
                if any(word in topic for topic in topics_lower):
                    matches = True
                    break
        
        if matches:
            matching_items.append(item)

    return [_format_explore_question(item, include_thumbnails) for item in matching_items]


@router.get("/thumbnails/{video_id}")
async def get_thumbnail(video_id: str):
    """
    Get thumbnail URL for a single video ID.
    This endpoint allows progressive loading - frontend can call it for each video
    without blocking the main response.
    """
    thumbnail = get_video_thumbnail(video_id)
    playlist_id = get_playlist_id(video_id) if video_id else None
    
    return {
        "videoId": video_id,
        "thumbnail": thumbnail,
        "playlistId": playlist_id
    }
