from fastapi import APIRouter, HTTPException, Query
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
import threading
import time
from app.services.cosmos_service import get_cosmos_container
from app.services.youtube_service import get_video_thumbnail
from app.services.llm_service import get_playlist_id

router = APIRouter()

# Topic counts and per-tag question lists rarely change. Cache in process
# memory (no Redis in this app) so Explore is instant after the first fill.
_TAGS_CACHE_TTL_SECONDS = 60 * 24 * 60 * 60
_tags_cache_lock = threading.Lock()
_tags_cache: Dict[str, Any] = {"expires_at": 0.0, "payload": None}
_corpus_lock = threading.Lock()
_corpus_cache: Dict[str, Any] = {"expires_at": 0.0, "items": None}

# Display label -> the raw topic strings (lowercase, as stored) that fold into it.
#
# Topics are free text generated by an LLM per question, so the same concept
# arrives under several spellings ('non-duality' / 'nondualism' / 'nonduality').
# Grouping them here keeps Explore from showing two tags for one idea, and stops
# questions from becoming unreachable because they were tagged with the variant.
#
# Membership rule: a topic earns a place once it has 5+ *answered* questions
# (those with a video_link -- the only ones Explore shows).
# Last refreshed: 2026-08-13 (527 docs) via scripts/analyze_topics_from_db.py
TOPIC_GROUPS: Dict[str, List[str]] = {
    'Consciousness':        ['consciousness'],
    'Philosophy':           ['philosophy'],
    'Meditation':           ['meditation'],
    'Enlightenment':        ['enlightenment', 'liberation'],
    'Advaita':              ['advaita'],
    'Karma':                ['karma'],
    'Suffering & Ethics':   ['suffering', 'ethics'],
    'Maya':                 ['maya'],
    'Mind':                 ['mind'],
    'Sleep':                ['sleep'],
    'AI':                   ['artificial intelligence'],
    'Buddhism':             ['buddhism'],
    'Theology':             ['theology'],
    'God & Devotion':       ['bhakti', 'devotion'],
    'Reality':              ['reality'],
    'Realization':          ['realization', 'self-realization'],
    'Reincarnation':        ['reincarnation', 'rebirth'],
    'Experience':           ['experience'],
    'Free Will':            ['free will'],
    'Mindfulness':          ['mindfulness'],
    'Non-Duality':          ['non-duality', 'nondualism', 'nonduality'],
    'Personal Development': ['personal development'],
    'Prayer':               ['prayer'],
    'Science':              ['science'],
    'Spiritual Life':       ['spiritual life'],
    'Spiritual Practice':   ['spiritual practice', 'spiritual practices'],
    'Universe':             ['universe'],
    'Yoga':                 ['yoga'],
    # New at the 5+ threshold as of the Aug 2026 refresh. Kept deliberately
    # separate rather than folded into adjacent tags: Self is not merged into
    # Consciousness, Death is not merged with afterlife, Dreams is not merged
    # with waking state.
    'Death':                ['death'],
    'Dreams':               ['dreams'],
    'Self':                 ['self'],
    'Truth':                ['truth'],
}

# Flat set of every grouped topic, for "does this question carry a main tag?"
ALL_GROUPED_TOPICS = {t for variants in TOPIC_GROUPS.values() for t in variants}


def get_main_tags() -> List[str]:
    """Display labels for all main tags."""
    return list(TOPIC_GROUPS.keys())


def _normalize_topics(topics) -> List[str]:
    if not isinstance(topics, list):
        return []
    return [t.lower().strip() for t in topics if t]


def get_answered_corpus() -> List[Dict]:
    """One Cosmos scan of answered questions; reused for tag counts and chip clicks."""
    now = time.monotonic()
    with _corpus_lock:
        items = _corpus_cache["items"]
        if items is not None and now < _corpus_cache["expires_at"]:
            return items

    container = get_cosmos_container()
    query = """
    SELECT c.questionText, c.video_link, c.topics
    FROM c
    WHERE IS_DEFINED(c.video_link)
      AND c.video_link != null
      AND c.video_link != ''
    """
    print("Loading answered questions corpus for Explore...")
    items = list(container.query_items(
        query=query,
        enable_cross_partition_query=True
    ))
    print(f"Loaded {len(items)} answered questions into Explore cache")
    with _corpus_lock:
        _corpus_cache["items"] = items
        _corpus_cache["expires_at"] = time.monotonic() + _TAGS_CACHE_TTL_SECONDS
    return items


def _format_explore_question(item: Dict, include_thumbnails: bool = False) -> Dict:
    video_link = item.get('video_link', '')
    base_url = video_link.split('&t=')[0] if '&t=' in video_link else video_link
    video_id = base_url.split('watch?v=')[1] if 'watch?v=' in base_url else None
    timestamp = _extract_timestamp_from_url(video_link)
    thumbnail = None
    playlist_id = None
    if include_thumbnails and video_id:
        thumbnail = get_video_thumbnail(video_id)
        playlist_id = get_playlist_id(video_id)
    return {
        "videoLink": base_url,
        "time": timestamp,
        "speakers": "Sarvapriyananda",
        "date": "2024-01-01",
        "region": None,
        "score": None,
        "answerViewPoint": None,
        "thumbnail": thumbnail,
        "questionTitle": item.get('questionText', ''),
        "playlistId": playlist_id
    }


def _extract_timestamp_from_url(video_link: str) -> str:
    """Extract timestamp from YouTube URL (format: &t=123s)."""
    if not video_link or '&t=' not in video_link:
        return ''
    try:
        time_part = video_link.split('&t=')[1].split('s')[0]
        seconds = int(time_part)
        hours = seconds // 3600
        minutes = (seconds % 3600) // 60
        secs = seconds % 60
        return f"{hours:02d}:{minutes:02d}:{secs:02d}"
    except:
        return ''


class TagInfo(BaseModel):
    tag: str
    count: int


class TaggedQuestion(BaseModel):
    question: str
    url: str
    timestamp: str
    video_title: str
    primary_tag: str
    tags: List[str]


def _compute_tags() -> List[TagInfo]:
    """Count tags from the in-memory answered corpus."""
    tag_counts: Dict[str, int] = {}
    other_count = 0

    for item in get_answered_corpus():
        topics = _normalize_topics(item.get('topics'))
        has_main_tag = False
        for label, variants in TOPIC_GROUPS.items():
            if any(topic in variants for topic in topics):
                tag_counts[label] = tag_counts.get(label, 0) + 1
                has_main_tag = True
        if topics and not has_main_tag:
            other_count += 1

    if other_count > 0:
        tag_counts['Other'] = other_count

    tags_list = [
        TagInfo(tag=tag, count=count)
        for tag, count in tag_counts.items()
    ]

    def sort_key(tag_info):
        if tag_info.tag.lower() == "other":
            return (1, tag_info.tag.lower())
        return (0, tag_info.tag.lower())

    tags = sorted(tags_list, key=sort_key)
    print(f"Computed {len(tags)} tags")
    return tags


def get_cached_tags() -> List[TagInfo]:
    now = time.monotonic()
    with _tags_cache_lock:
        payload = _tags_cache["payload"]
        if payload is not None and now < _tags_cache["expires_at"]:
            return payload

    payload = _compute_tags()
    with _tags_cache_lock:
        _tags_cache["payload"] = payload
        _tags_cache["expires_at"] = time.monotonic() + _TAGS_CACHE_TTL_SECONDS
    return payload


def warm_tags_cache() -> None:
    """Fill the answered corpus so Explore chips and lists are in memory."""
    get_answered_corpus()
    get_cached_tags()


@router.get("/tags", response_model=List[TagInfo])
async def get_tags():
    """Get all available tags with question counts from Cosmos DB."""
    try:
        return get_cached_tags()
    except Exception as e:
        print(f"Error in get_tags endpoint: {e}")
        import traceback
        print(traceback.format_exc())
        raise HTTPException(status_code=500, detail=f"Error fetching tags: {str(e)}")


@router.get("/tags/{tag}/questions", response_model=List[Dict])
async def get_questions_by_tag(tag: str, include_thumbnails: bool = Query(False, description="Include thumbnails (slower but better UX)")):
    """Get all questions for a specific tag from the in-memory corpus."""
    tag_lower = tag.lower()
    items = get_answered_corpus()
    questions = []

    if tag_lower == "other":
        for item in items:
            topics = _normalize_topics(item.get('topics'))
            if topics and not any(t in ALL_GROUPED_TOPICS for t in topics):
                questions.append(_format_explore_question(item, include_thumbnails))
        return questions

    matching_label = next(
        (label for label in TOPIC_GROUPS if label.lower() == tag_lower), None
    )
    if not matching_label:
        return []

    variants = set(TOPIC_GROUPS[matching_label])
    for item in items:
        topics = _normalize_topics(item.get('topics'))
        if any(t in variants for t in topics):
            questions.append(_format_explore_question(item, include_thumbnails))
    return questions


@router.get("/tags/search", response_model=List[Dict])
async def search_questions_by_topic(query: str, include_thumbnails: bool = Query(False, description="Include thumbnails (slower but better UX)")):
    """Search questions by topic/keyword against the in-memory corpus."""
    if not query or not query.strip():
        return []

    query_lower = query.lower().strip()
    query_words = query_lower.split()
    items = get_answered_corpus()
    
    # Filter in Python for flexible matching
    matching_items = []
    for item in items:
        question_text = item.get('questionText', '').lower()
        topics = item.get('topics', [])
        topics_lower = [t.lower() if t else '' for t in topics]
        
        matches = False
        
        # Check if all query words are in question text
        if all(word in question_text for word in query_words):
            matches = True
        
        # Check if query matches any topic (case-insensitive, partial match)
        if not matches:
            for topic in topics_lower:
                if query_lower in topic or topic in query_lower:
                    matches = True
                    break
        
        # Check if any query word matches any topic
        if not matches:
            for word in query_words:
                if any(word in topic for topic in topics_lower):
                    matches = True
                    break
        
        if matches:
            matching_items.append(item)

    return [_format_explore_question(item, include_thumbnails) for item in matching_items]


@router.get("/thumbnails/{video_id}")
async def get_thumbnail(video_id: str):
    """
    Get thumbnail URL for a single video ID.
    This endpoint allows progressive loading - frontend can call it for each video
    without blocking the main response.
    """
    thumbnail = get_video_thumbnail(video_id)
    playlist_id = get_playlist_id(video_id) if video_id else None
    
    return {
        "videoId": video_id,
        "thumbnail": thumbnail,
        "playlistId": playlist_id
    }
