from fastapi import APIRouter, HTTPException, Query
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
import threading
import time
from app.services.cosmos_service import get_cosmos_container
from app.services.youtube_service import get_video_thumbnail
from app.services.llm_service import get_playlist_id

router = APIRouter()

# Topic counts and per-tag question lists rarely change. Cache in process
# memory (no Redis in this app) so Explore is instant after the first fill.
_TAGS_CACHE_TTL_SECONDS = 30 * 60
_tags_cache_lock = threading.Lock()
_tags_cache: Dict[str, Any] = {"expires_at": 0.0, "payload": None}
_questions_cache_lock = threading.Lock()
_questions_cache: Dict[tuple, Dict[str, Any]] = {}

# Display label -> the raw topic strings (lowercase, as stored) that fold into it.
#
# Topics are free text generated by an LLM per question, so the same concept
# arrives under several spellings ('non-duality' / 'nondualism' / 'nonduality').
# Grouping them here keeps Explore from showing two tags for one idea, and stops
# questions from becoming unreachable because they were tagged with the variant.
#
# Membership rule: a topic earns a place once it has 5+ *answered* questions
# (those with a video_link -- the only ones Explore shows).
# Last refreshed: 2026-08-13 (527 docs) via scripts/analyze_topics_from_db.py
TOPIC_GROUPS: Dict[str, List[str]] = {
    'Consciousness':        ['consciousness'],
    'Philosophy':           ['philosophy'],
    'Meditation':           ['meditation'],
    'Enlightenment':        ['enlightenment', 'liberation'],
    'Advaita':              ['advaita'],
    'Karma':                ['karma'],
    'Suffering & Ethics':   ['suffering', 'ethics'],
    'Maya':                 ['maya'],
    'Mind':                 ['mind'],
    'Sleep':                ['sleep'],
    'AI':                   ['artificial intelligence'],
    'Buddhism':             ['buddhism'],
    'Theology':             ['theology'],
    'God & Devotion':       ['bhakti', 'devotion'],
    'Reality':              ['reality'],
    'Realization':          ['realization', 'self-realization'],
    'Reincarnation':        ['reincarnation', 'rebirth'],
    'Experience':           ['experience'],
    'Free Will':            ['free will'],
    'Mindfulness':          ['mindfulness'],
    'Non-Duality':          ['non-duality', 'nondualism', 'nonduality'],
    'Personal Development': ['personal development'],
    'Prayer':               ['prayer'],
    'Science':              ['science'],
    'Spiritual Life':       ['spiritual life'],
    'Spiritual Practice':   ['spiritual practice', 'spiritual practices'],
    'Universe':             ['universe'],
    'Yoga':                 ['yoga'],
    # New at the 5+ threshold as of the Aug 2026 refresh. Kept deliberately
    # separate rather than folded into adjacent tags: Self is not merged into
    # Consciousness, Death is not merged with afterlife, Dreams is not merged
    # with waking state.
    'Death':                ['death'],
    'Dreams':               ['dreams'],
    'Self':                 ['self'],
    'Truth':                ['truth'],
}

# Flat set of every grouped topic, for "does this question carry a main tag?"
ALL_GROUPED_TOPICS = {t for variants in TOPIC_GROUPS.values() for t in variants}


def get_main_tags() -> List[str]:
    """Display labels for all main tags."""
    return list(TOPIC_GROUPS.keys())


def _topics_predicate(variants: List[str]) -> tuple:
    """Build a SQL predicate matching a document tagged with ANY variant.

    Returns (predicate_sql, parameters). COUNT(1) over this counts documents,
    so a question tagged both 'enlightenment' and 'liberation' counts once.
    """
    clauses = " OR ".join(
        f"ARRAY_CONTAINS(c.topics, @t{i}, true)" for i in range(len(variants))
    )
    params = [{"name": f"@t{i}", "value": v} for i, v in enumerate(variants)]
    return f"({clauses})", params


def _extract_timestamp_from_url(video_link: str) -> str:
    """Extract timestamp from YouTube URL (format: &t=123s)."""
    if not video_link or '&t=' not in video_link:
        return ''
    try:
        time_part = video_link.split('&t=')[1].split('s')[0]
        seconds = int(time_part)
        hours = seconds // 3600
        minutes = (seconds % 3600) // 60
        secs = seconds % 60
        return f"{hours:02d}:{minutes:02d}:{secs:02d}"
    except:
        return ''


class TagInfo(BaseModel):
    tag: str
    count: int


class TaggedQuestion(BaseModel):
    question: str
    url: str
    timestamp: str
    video_title: str
    primary_tag: str
    tags: List[str]


def _compute_tags() -> List[TagInfo]:
    """Query Cosmos for tag counts. Slow; callers should use the cache."""
    container = get_cosmos_container()
    tag_counts: Dict[str, int] = {}

    for label, variants in TOPIC_GROUPS.items():
        predicate, parameters = _topics_predicate(variants)
        query = f"""
        SELECT VALUE COUNT(1)
        FROM c
        WHERE {predicate}
          AND IS_DEFINED(c.video_link)
          AND c.video_link != null
          AND c.video_link != ''
        """

        try:
            result = list(container.query_items(
                query=query,
                parameters=parameters,
                enable_cross_partition_query=True
            ))
            count = result[0] if result else 0
            if count > 0:
                tag_counts[label] = count
        except Exception as e:
            print(f"Error counting tag {label}: {e}")
            import traceback
            print(traceback.format_exc())
            continue

    # Count "Other" - questions that don't have any main tag
    query = """
    SELECT c.topics
    FROM c
    WHERE IS_DEFINED(c.topics)
      AND IS_ARRAY(c.topics) = true
      AND IS_DEFINED(c.video_link)
      AND c.video_link != null
      AND c.video_link != ''
    """

    try:
        print("Counting 'Other' tag - this may take a moment...")
        items = list(container.query_items(
            query=query,
            enable_cross_partition_query=True
        ))
        print(f"Fetched {len(items)} items for 'Other' count")

        other_count = 0
        for item in items:
            topics = item.get('topics', [])
            if not isinstance(topics, list):
                continue

            has_main_tag = False
            for topic in topics:
                if topic and topic.lower().strip() in ALL_GROUPED_TOPICS:
                    has_main_tag = True
                    break

            if not has_main_tag:
                other_count += 1

        if other_count > 0:
            tag_counts['Other'] = other_count
            print(f"Found {other_count} questions in 'Other' category")
    except Exception as e:
        print(f"Error counting Other: {e}")
        import traceback
        print(traceback.format_exc())

    tags_list = [
        TagInfo(tag=tag, count=count)
        for tag, count in tag_counts.items()
    ]

    def sort_key(tag_info):
        if tag_info.tag.lower() == "other":
            return (1, tag_info.tag.lower())
        return (0, tag_info.tag.lower())

    tags = sorted(tags_list, key=sort_key)
    print(f"Computed {len(tags)} tags")
    return tags


def get_cached_tags() -> List[TagInfo]:
    now = time.monotonic()
    with _tags_cache_lock:
        payload = _tags_cache["payload"]
        if payload is not None and now < _tags_cache["expires_at"]:
            return payload

    payload = _compute_tags()
    with _tags_cache_lock:
        _tags_cache["payload"] = payload
        _tags_cache["expires_at"] = time.monotonic() + _TAGS_CACHE_TTL_SECONDS
    return payload


def warm_tags_cache() -> None:
    """Fill the tags cache so the first Explore request is not a Cosmos scan."""
    get_cached_tags()


@router.get("/tags", response_model=List[TagInfo])
async def get_tags():
    """Get all available tags with question counts from Cosmos DB."""
    try:
        return get_cached_tags()
    except Exception as e:
        print(f"Error in get_tags endpoint: {e}")
        import traceback
        print(traceback.format_exc())
        raise HTTPException(status_code=500, detail=f"Error fetching tags: {str(e)}")


@router.get("/tags/{tag}/questions", response_model=List[Dict])
async def get_questions_by_tag(tag: str, include_thumbnails: bool = Query(False, description="Include thumbnails (slower but better UX)")):
    """Get all questions for a specific tag from Cosmos DB."""
    cache_key = (tag.lower(), include_thumbnails)
    now = time.monotonic()
    with _questions_cache_lock:
        cached = _questions_cache.get(cache_key)
        if cached and now < cached["expires_at"]:
            return cached["payload"]

    container = get_cosmos_container()

    tag_lower = tag.lower()
    
    # Handle "Other" tag - questions that don't have any main tags
    if tag_lower == "other":
        # Build query to exclude all main tags
        query = """
        SELECT c.id, c.questionText, c.video_link, c.topics
        FROM c
        WHERE IS_DEFINED(c.video_link) 
          AND c.video_link != null 
          AND c.video_link != ''
          AND IS_DEFINED(c.topics) 
          AND IS_ARRAY(c.topics) = true
        """
        
        items = list(container.query_items(
            query=query,
            enable_cross_partition_query=True
        ))
        
        # Filter out questions that have any main tag
        other_questions = []
        for item in items:
            topics = item.get('topics', [])
            has_main_tag = False
            for topic in topics:
                if topic and topic.lower().strip() in ALL_GROUPED_TOPICS:
                    has_main_tag = True
                    break
            if not has_main_tag:
                other_questions.append(item)
        
        questions = []
        for item in other_questions:
            # Extract timestamp from video_link if present
            video_link = item.get('video_link', '')
            base_url = video_link.split('&t=')[0] if '&t=' in video_link else video_link
            video_id = base_url.split('watch?v=')[1] if 'watch?v=' in base_url else None
            timestamp = _extract_timestamp_from_url(video_link)
            
            # Get thumbnail and playlist_id only if requested
            thumbnail = None
            playlist_id = None
            if include_thumbnails and video_id:
                thumbnail = get_video_thumbnail(video_id)
                playlist_id = get_playlist_id(video_id)
            
            questions.append({
                "videoLink": base_url,
                "time": timestamp,
                "speakers": "Sarvapriyananda",
                "date": "2024-01-01",  # Placeholder
                "region": None,
                "score": None,
                "answerViewPoint": None,
                "thumbnail": thumbnail,
                "questionTitle": item.get('questionText', ''),
                "playlistId": playlist_id
            })
        
        with _questions_cache_lock:
            _questions_cache[cache_key] = {
                "expires_at": time.monotonic() + _TAGS_CACHE_TTL_SECONDS,
                "payload": questions,
            }
        return questions
    
    # For specific tags, resolve the display label to its topic group
    matching_label = next(
        (label for label in TOPIC_GROUPS if label.lower() == tag_lower), None
    )

    if not matching_label:
        return []

    # Match questions carrying ANY topic variant in the group, so a question
    # tagged 'liberation' surfaces under Enlightenment alongside the rest.
    predicate, parameters = _topics_predicate(TOPIC_GROUPS[matching_label])
    query = f"""
    SELECT c.id, c.questionText, c.video_link, c.topics
    FROM c
    WHERE {predicate}
      AND IS_DEFINED(c.video_link)
      AND c.video_link != null
      AND c.video_link != ''
    """

    items = list(container.query_items(
        query=query,
        parameters=parameters,
        enable_cross_partition_query=True
    ))
    
    # Convert to response format (AnswerResponse format)
    questions = []
    for item in items:
        video_link = item.get('video_link', '')
        base_url = video_link.split('&t=')[0] if '&t=' in video_link else video_link
        video_id = base_url.split('watch?v=')[1] if 'watch?v=' in base_url else None
        timestamp = _extract_timestamp_from_url(video_link)
        
        # Get thumbnail and playlist_id only if requested
        thumbnail = None
        playlist_id = None
        if include_thumbnails and video_id:
            thumbnail = get_video_thumbnail(video_id)
            playlist_id = get_playlist_id(video_id)
        
        questions.append({
            "videoLink": base_url,
            "time": timestamp,
            "speakers": "Sarvapriyananda",
            "date": "2024-01-01",  # Placeholder
            "region": None,
            "score": None,
            "answerViewPoint": None,
            "thumbnail": thumbnail,
            "questionTitle": item.get('questionText', ''),
            "playlistId": playlist_id
        })

    with _questions_cache_lock:
        _questions_cache[cache_key] = {
            "expires_at": time.monotonic() + _TAGS_CACHE_TTL_SECONDS,
            "payload": questions,
        }
    return questions


@router.get("/tags/search", response_model=List[Dict])
async def search_questions_by_topic(query: str, include_thumbnails: bool = Query(False, description="Include thumbnails (slower but better UX)")):
    """Search questions by topic/keyword in Cosmos DB."""
    if not query or not query.strip():
        return []
    
    container = get_cosmos_container()
    query_lower = query.lower().strip()
    query_words = query_lower.split()
    
    # Build query to search in topics array and question text
    # We'll do case-insensitive matching in Python for now
    # (Cosmos DB ARRAY_CONTAINS with true flag does case-insensitive, but we need partial matching)
    
    sql_query = """
    SELECT c.id, c.questionText, c.video_link, c.topics
    FROM c
    WHERE IS_DEFINED(c.video_link) 
      AND c.video_link != null 
      AND c.video_link != ''
      AND IS_DEFINED(c.topics) 
      AND IS_ARRAY(c.topics) = true
    """
    
    items = list(container.query_items(
        query=sql_query,
        enable_cross_partition_query=True
    ))
    
    # Filter in Python for flexible matching
    matching_items = []
    for item in items:
        question_text = item.get('questionText', '').lower()
        topics = item.get('topics', [])
        topics_lower = [t.lower() if t else '' for t in topics]
        
        matches = False
        
        # Check if all query words are in question text
        if all(word in question_text for word in query_words):
            matches = True
        
        # Check if query matches any topic (case-insensitive, partial match)
        if not matches:
            for topic in topics_lower:
                if query_lower in topic or topic in query_lower:
                    matches = True
                    break
        
        # Check if any query word matches any topic
        if not matches:
            for word in query_words:
                if any(word in topic for topic in topics_lower):
                    matches = True
                    break
        
        if matches:
            matching_items.append(item)
    
    # Convert to response format (AnswerResponse format)
    questions = []
    
    # Fetch thumbnails sequentially if requested (safer than parallel, avoids SSL issues)
    if include_thumbnails and matching_items:
        for item in matching_items:
            video_link = item.get('video_link', '')
            base_url = video_link.split('&t=')[0] if '&t=' in video_link else video_link
            video_id = base_url.split('watch?v=')[1] if 'watch?v=' in base_url else None
            timestamp = _extract_timestamp_from_url(video_link)
            
            thumbnail = None
            playlist_id = None
            if video_id:
                thumbnail = get_video_thumbnail(video_id)
                playlist_id = get_playlist_id(video_id)
            
            questions.append({
                "videoLink": base_url,
                "time": timestamp,
                "speakers": "Sarvapriyananda",
                "date": "2024-01-01",  # Placeholder
                "region": None,
                "score": None,
                "answerViewPoint": None,
                "thumbnail": thumbnail,
                "questionTitle": item.get('questionText', ''),
                "playlistId": playlist_id
            })
    else:
        # Fast path: skip thumbnails
        for item in matching_items:
            video_link = item.get('video_link', '')
            base_url = video_link.split('&t=')[0] if '&t=' in video_link else video_link
            timestamp = _extract_timestamp_from_url(video_link)
            
            questions.append({
                "videoLink": base_url,
                "time": timestamp,
                "speakers": "Sarvapriyananda",
                "date": "2024-01-01",  # Placeholder
                "region": None,
                "score": None,
                "answerViewPoint": None,
                "thumbnail": None,  # Skip thumbnail for faster response
                "questionTitle": item.get('questionText', ''),
                "playlistId": None
            })
    
    return questions


@router.get("/thumbnails/{video_id}")
async def get_thumbnail(video_id: str):
    """
    Get thumbnail URL for a single video ID.
    This endpoint allows progressive loading - frontend can call it for each video
    without blocking the main response.
    """
    thumbnail = get_video_thumbnail(video_id)
    playlist_id = get_playlist_id(video_id) if video_id else None
    
    return {
        "videoId": video_id,
        "thumbnail": thumbnail,
        "playlistId": playlist_id
    }
